In [177]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,r2_score,mean_absolute_error,mean_absolute_percentage_error,mean_squared_error
from matplotlib import style
import warnings
warnings.filterwarnings('ignore') # hide annoying warnings
style.use('fivethirtyeight') # for more appealing vizs




In [178]:
#read data 

In [179]:
df = pd.read_csv("C:\\Users\\ML project\\mushrooms.csv")
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [180]:
#checking missing values

In [181]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [183]:
df.shape

(8124, 23)

In [184]:
df['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [185]:
df["class"].unique()

array(['p', 'e'], dtype=object)

In [186]:
#change datatype object to category

In [187]:
df = df.astype('category')

In [188]:
#encoding

In [189]:
labelencoder=LabelEncoder()
for column in df.columns:
    df[column] = labelencoder.fit_transform(df[column])

In [190]:
#defining x and y

In [191]:
x = df.iloc[:,1:]
x

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 22 columns]

In [192]:
y = df.iloc[:,0]
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int32

In [193]:
#feature selection

In [194]:
from sklearn import datasets
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [195]:
chi2_selector = SelectKBest(chi2, k=15)
x_kbest = chi2_selector.fit_transform(x,y)
arr = chi2_selector.get_support()
arr

array([False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True])

In [196]:
l = list(arr)
l1=[]
j=0
for i in x.columns:
  if l[j]==True:
    l1.append(i)
  j+=1

x_new = x[l1]
x_new.head()

cap-surface  bruises  odor  gill-spacing  gill-size  gill-color  \
0            2        1     6             0          1           4   
1            2        1     0             0          0           4   
2            2        1     3             0          0           5   
3            3        1     6             0          1           5   
4            2        0     5             1          0           4   

   stalk-root  stalk-surface-above-ring  stalk-surface-below-ring  \
0           3                         2                         2   
1           2                         2                         2   
2           2                         2                         2   
3           3                         2                         2   
4           3                         2                         2   

   stalk-color-above-ring  stalk-color-below-ring  ring-type  \
0                       7                       7          4   
1                       7                       7          4   
2                       7                       7          4   
3                       7                       7          4   
4                       7                       7          0   

   spore-print-color  population  habitat  
0                  2           3        5  
1                  3           2        1  
2                  3           2        3  
3                  2           3        5  
4                  3           0        1

In [197]:
print('Original number of features:', x.shape)
print('Reduced number of features:', x_kbest.shape)

Original number of features: (8124, 22)
Reduced number of features: (8124, 15)


In [198]:
#traing and testing

In [199]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y, random_state=42, test_size=0.25) 

In [200]:
x_train.shape

(6093, 15)

In [201]:
#Random Forest Classifier

In [202]:



#import libraries 
from sklearn.ensemble import RandomForestClassifier
#create the instance of the model
rf=RandomForestClassifier()
#train the data
rf.fit(x_train,y_train)
#predict x_test
y_predict=rf.predict(x_test)


In [203]:
#check the performance of the model
print('Accuracy is :', accuracy_score(y_test,y_predict))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_predict)))
print('r2 Score is :', r2_score(y_test,y_predict))

Accuracy is : 1.0
RMSE: 0.0
r2 Score is : 1.0


In [204]:
confusion_matrix(y_test, y_predict)

array([[1040,    0],
       [   0,  991]], dtype=int64)

In [205]:
rf.score(x_train,y_train)

1.0

In [206]:
rf.score(x_test,y_test)

1.0

In [207]:
#Desicion Tree Classifier

In [208]:


#import library
from sklearn.tree import DecisionTreeClassifier
#create an instance of the model
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
y_predict = dt_model.predict(x_test)





In [209]:
#check the performance of the model
print('Accuracy is :', accuracy_score(y_test,y_predict))

print('RMSE:',np.sqrt(mean_squared_error(y_test,y_predict)))

print('r2 Score is :', r2_score(y_test,y_predict))

Accuracy is : 1.0
RMSE: 0.0
r2 Score is : 1.0


In [210]:
confusion_matrix(y_test, y_predict)

array([[1040,    0],
       [   0,  991]], dtype=int64)

In [211]:
dt_model.score(x_train,y_train)

1.0

In [212]:
dt_model.score(x_test,y_test)

1.0

In [213]:
#support vector

In [214]:
#SVC
from sklearn.svm import SVC

svcChi= SVC()

svcChi.fit(x_train,y_train)

y_predict = svcChi.predict(x_test)

In [215]:
#check the performance of the model
print('Accuracy is :', accuracy_score(y_test,y_predict))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_predict)))
print('r2 Score is :', r2_score(y_test,y_predict))

Accuracy is : 0.9876907927129492
RMSE: 0.11094686695464057
r2 Score is : 0.9507344950710238


In [216]:
confusion_matrix(y_test, y_predict)

array([[1033,    7],
       [  18,  973]], dtype=int64)

In [217]:
svcChi.score(x_train,y_train)

0.98703430165764

In [218]:
svcChi.score(x_test,y_test)

0.9876907927129492

In [219]:
#logistic regression

In [220]:
logit_model = LogisticRegression()
logit_model = logit_model.fit(x_train, y_train)
y_predict = logit_model.predict(x_test)
y_predict

array([0, 1, 1, ..., 0, 0, 1])

In [221]:
#check the performance of the model
print('Accuracy is :', accuracy_score(y_test,y_predict))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_predict)))
print('r2 Score is :', r2_score(y_test,y_predict))

Accuracy is : 0.9438700147710487
RMSE: 0.23691767605848083
r2 Score is : 0.7753492975238687


In [222]:
confusion_matrix(y_test, y_predict)

array([[982,  58],
       [ 56, 935]], dtype=int64)

In [223]:
logit_model.score(x_train,y_train)

0.9433776464795667

In [224]:
logit_model.score(x_test,y_test)

0.9438700147710487

In [225]:
#create pickle file

In [226]:
import pickle

with open('model.pickle', 'wb') as f:
    pickle.dump(svcChi,f)

In [227]:
with open('model.pickle', 'rb') as f:
    model=pickle.load(f)

In [228]:
#checking for pickle file

In [229]:
input = np.array([[2,1,6,0,1,4,3,2,2,7,7,4,2,3,5]])
x = model.predict(input)
print(x)

[1]
